version: '3.8'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/src/app
      - ./audio_files:/usr/src/app/audio_files
    environment:
      FASTAPI_APP: app.main:app
      FASTAPI_ENV: development
      FASTAPI_RUN_HOST: 0.0.0.0
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

volumes:
  redis_data:
